### ISSUE TITLE
Reddit server errors spam the console but are non-fatal

### ISSUE THREAD

**Issue by leftbones** [evprkr/DiceBot#6]
If the bot tries to check its inbox and receives a server error 500 or something similar, it spams the console with error messages, but doesn't crash, just carries on.

**Comment by evprkr** [comment]
Fixed in 578448b, server errors now output a cleaner message stating that the bot will try again in _n_ seconds (specified in the bot settings) then the message is overwritten by the next console output so as to not fill up the console with the same error.

**Comment by leftbones** [comment]
Fixed in 578448b, server errors now output a cleaner message stating that the bot will try again in _n_ seconds (specified in the bot settings) then the message is overwritten by the next console output so as to not fill up the console with the same error.
